# General configuration for acoustic_ekf_pkg
process_noise: 0.01
measurement_noise: 0.1

# Initialization parameters
leader_init_samples: 1
follower_init_samples: 1
dt: 0.005  # Time step for the EKF

# ROS topic names for reading and publishing
publish_topic: '/follower/ekf/state'
geopoint_topic: '/follower/ekf/geopoint'
dist1_topic: '/leader1/distance'
dist2_topic: '/leader2/distance'
gps1_topic: '/leader1/gps'
gps2_topic: '/leader2/gps'
# follower_gps_topic: '/lolo/smarc/latlon'
follower_gps_topic: '/lolo/standard/navsatfix'
follower_gps_type: 'NavSatFix' # 'GeoPoint' or 'NavSatFix'
imu_topic: '/lolo/standard/imu'

depth_topic: '/lolo/smarc/depth'

# Other parameters
max_speed: 500  # Maximum allowed speed for all vehicles (m/s)
correction_factor: 1  # Correction factor for distance measurements
update_cooldown: 0  # Minimum seconds between EKF updates
leader_gps_type: NavSatFix  # Options: 'NavSatFix' or 'GeoPoint'
leader_depth: 0.5  # Depth offset to subtract from measured depth for horizontal distance calculation
# You can add more parameters below as needed
# Example:
# initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# use_leader_velocities: false
