# General configuration for acoustic_ekf_pkg
process_noise: 4
measurement_noise: 2
distance_measurement_noise: 0.1  # if different, adjust; using same scale here

# Initialization parameters
leader_init_samples: 1
follower_init_samples: 1

# ROS topic names for reading and publishing
publish_topic: '/follower/ekf/state'
geopoint_topic: '/follower/ekf_w_head/geopoint'
dist1_topic: '/leader1/distance'
dist2_topic: '/leader2/distance'
gps1_topic: '/leader1/gps'
gps2_topic: '/leader2/gps'
# follower_gps_topic: '/lolo/smarc/latlon'
follower_gps_topic: '/lolo/standard/navsatfix'
follower_gps_type: 'NavSatFix' # 'GeoPoint' or 'NavSatFix'
imu_topic: '/lolo/standard/imu'

depth_topic: '/lolo/smarc/depth'

# Other parameters
max_speed: 500.0  # Maximum allowed speed for all vehicles (m/s)
correction_factor: 0.9824  # 1473.6 / 1500 acoustic distance correction factor
update_cooldown: 0  # Minimum seconds between EKF updates
leader_gps_type: NavSatFix  # Options: 'NavSatFix' or 'GeoPoint'
leader_depth: 1  # Leaders operating depth
heading_measurement_noise: 5  # degrees
heading_perturbation: 0  # degrees (+/- uniform)
use_heading_updates: true # Toggle heading updates
boat_offset: [0.0, -0.6]
# You can add more parameters below as needed
# Example:
# initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# use_leader_velocities: false
